// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: effect_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EffectConfig {

  /// <summary>Holder for reflection information generated from effect_config.proto</summary>
  public static partial class EffectConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for effect_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EffectConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNlZmZlY3RfY29uZmlnLnByb3RvEg1lZmZlY3RfY29uZmlnGhVza2lsbG5l",
            "d19jb25maWcucHJvdG8irAYKC2VmZmVjdF9kYXRhEg8KAklkGAEgASgNSACI",
            "AQESEQoETmFtZRgCIAEoCUgBiAEBEhEKBFBhdGgYAyABKAlIAogBARISCgVT",
            "Y2FsZRgEIAEoAkgDiAEBEhUKCExpZmVUaW1lGAUgASgCSASIAQESFQoIT25F",
            "bnRpdHkYBiABKAhIBYgBARIWCglOZWVkSGlnaHQYByABKAhIBogBARIUCgdQ",
            "b3NOYW1lGAggASgJSAeIAQESGAoLTm9SZXBlYXRBZGQYCSABKAhICIgBARIe",
            "ChFBZGl1c3RTa2lsbEhlaWdodBgKIAEoCEgJiAEBEhoKDVNjYWxlV2l0aFVu",
            "aXQYCyABKAhICogBARIaCg1TaG93R3JvdXBEaWZmGAwgASgISAuIAQESFQoI",
            "SGFzVHJhaWwYDSABKAhIDIgBARIZCgxEZWFkTGVmdFRpbWUYDiABKA1IDYgB",
            "ARIhChROb3RSZW1vdmVPblNraWxsT3ZlchgPIAEoCEgOiAEBEiQKF1JlbW92",
            "ZU9uU2tpbGxBY3Rpb25PdmVyGBAgASgISA+IAQESFAoHUHJpb3J0eRgRIAEo",
            "BUgQiAEBEjMKD0VmZmVjdE92ZXJUeXBlcxgSIAMoDjIaLnNraWxsbmV3X2Nv",
            "bmZpZy5FT3ZlclR5cGUSPgoTRWZmZWN0RW5kR2FtZUV2ZW50cxgTIAMoDjIh",
            "LnNraWxsbmV3X2NvbmZpZy5FRW50aXR5R2FtZUV2ZW50QgUKA19JZEIHCgVf",
            "TmFtZUIHCgVfUGF0aEIICgZfU2NhbGVCCwoJX0xpZmVUaW1lQgsKCV9PbkVu",
            "dGl0eUIMCgpfTmVlZEhpZ2h0QgoKCF9Qb3NOYW1lQg4KDF9Ob1JlcGVhdEFk",
            "ZEIUChJfQWRpdXN0U2tpbGxIZWlnaHRCEAoOX1NjYWxlV2l0aFVuaXRCEAoO",
            "X1Nob3dHcm91cERpZmZCCwoJX0hhc1RyYWlsQg8KDV9EZWFkTGVmdFRpbWVC",
            "FwoVX05vdFJlbW92ZU9uU2tpbGxPdmVyQhoKGF9SZW1vdmVPblNraWxsQWN0",
            "aW9uT3ZlckIKCghfUHJpb3J0eSLJAQoJY29udGFpbmVyEhEKBG5hbWUYASAB",
            "KAlIAIgBARIVCghidWlsZF9pZBgCIAEoBUgBiAEBEjIKBWluZm9zGAMgAygL",
            "MiMuZWZmZWN0X2NvbmZpZy5jb250YWluZXIuSW5mb3NFbnRyeRpICgpJbmZv",
            "c0VudHJ5EgsKA2tleRgBIAEoBRIpCgV2YWx1ZRgCIAEoCzIaLmVmZmVjdF9j",
            "b25maWcuZWZmZWN0X2RhdGE6AjgBQgcKBV9uYW1lQgsKCV9idWlsZF9pZCqi",
            "AQoKRUF0dGFjaFBvcxIOCgpkdW1teV9ub25lEAASDQoJZHVtbXlfdG9wEAES",
            "EAoMZHVtbXlfYm90dG9tEAISEAoMZHVtbXlfY2VudGVyEAMSDwoLZHVtbXlf",
            "bGhhbmQQBBIPCgtkdW1teV9yaGFuZBAFEg4KCmR1bW15X2JvZHkQBhIPCgtk",
            "dW1teV93aW5ncxAHEg4KCmR1bW15X2hlYWQQCGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::SkillnewConfig.SkillnewConfigReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EffectConfig.EAttachPos), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EffectConfig.effect_data), global::EffectConfig.effect_data.Parser, new[]{ "Id", "Name", "Path", "Scale", "LifeTime", "OnEntity", "NeedHight", "PosName", "NoRepeatAdd", "AdiustSkillHeight", "ScaleWithUnit", "ShowGroupDiff", "HasTrail", "DeadLeftTime", "NotRemoveOnSkillOver", "RemoveOnSkillActionOver", "Priorty", "EffectOverTypes", "EffectEndGameEvents" }, new[]{ "Id", "Name", "Path", "Scale", "LifeTime", "OnEntity", "NeedHight", "PosName", "NoRepeatAdd", "AdiustSkillHeight", "ScaleWithUnit", "ShowGroupDiff", "HasTrail", "DeadLeftTime", "NotRemoveOnSkillOver", "RemoveOnSkillActionOver", "Priorty" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EffectConfig.container), global::EffectConfig.container.Parser, new[]{ "Name", "BuildId", "Infos" }, new[]{ "Name", "BuildId" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Enums
  public enum EAttachPos {
    [pbr::OriginalName("dummy_none")] DummyNone = 0,
    [pbr::OriginalName("dummy_top")] DummyTop = 1,
    [pbr::OriginalName("dummy_bottom")] DummyBottom = 2,
    [pbr::OriginalName("dummy_center")] DummyCenter = 3,
    [pbr::OriginalName("dummy_lhand")] DummyLhand = 4,
    [pbr::OriginalName("dummy_rhand")] DummyRhand = 5,
    [pbr::OriginalName("dummy_body")] DummyBody = 6,
    [pbr::OriginalName("dummy_wings")] DummyWings = 7,
    [pbr::OriginalName("dummy_head")] DummyHead = 8,
  }

  #endregion

  #region Messages
  public sealed partial class effect_data : pb::IMessage<effect_data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<effect_data> _parser = new pb::MessageParser<effect_data>(() => new effect_data());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<effect_data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EffectConfig.EffectConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public effect_data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public effect_data(effect_data other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      name_ = other.name_;
      path_ = other.path_;
      scale_ = other.scale_;
      lifeTime_ = other.lifeTime_;
      onEntity_ = other.onEntity_;
      needHight_ = other.needHight_;
      posName_ = other.posName_;
      noRepeatAdd_ = other.noRepeatAdd_;
      adiustSkillHeight_ = other.adiustSkillHeight_;
      scaleWithUnit_ = other.scaleWithUnit_;
      showGroupDiff_ = other.showGroupDiff_;
      hasTrail_ = other.hasTrail_;
      deadLeftTime_ = other.deadLeftTime_;
      notRemoveOnSkillOver_ = other.notRemoveOnSkillOver_;
      removeOnSkillActionOver_ = other.removeOnSkillActionOver_;
      priorty_ = other.priorty_;
      effectOverTypes_ = other.effectOverTypes_.Clone();
      effectEndGameEvents_ = other.effectEndGameEvents_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public effect_data Clone() {
      return new effect_data(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    /// <summary>
    ///特效id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "Id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "Id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_;
    /// <summary>
    ///特效名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? ""; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "Name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "Name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "Path" field.</summary>
    public const int PathFieldNumber = 3;
    private string path_;
    /// <summary>
    ///特效路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Path {
      get { return path_ ?? ""; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "Path" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPath {
      get { return path_ != null; }
    }
    /// <summary>Clears the value of the "Path" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPath() {
      path_ = null;
    }

    /// <summary>Field number for the "Scale" field.</summary>
    public const int ScaleFieldNumber = 4;
    private float scale_;
    /// <summary>
    ///特效缩放
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Scale {
      get { if ((_hasBits0 & 2) != 0) { return scale_; } else { return 0F; } }
      set {
        _hasBits0 |= 2;
        scale_ = value;
      }
    }
    /// <summary>Gets whether the "Scale" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasScale {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "Scale" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearScale() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "LifeTime" field.</summary>
    public const int LifeTimeFieldNumber = 5;
    private float lifeTime_;
    /// <summary>
    ///特效生命
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float LifeTime {
      get { if ((_hasBits0 & 4) != 0) { return lifeTime_; } else { return 0F; } }
      set {
        _hasBits0 |= 4;
        lifeTime_ = value;
      }
    }
    /// <summary>Gets whether the "LifeTime" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLifeTime {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "LifeTime" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLifeTime() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "OnEntity" field.</summary>
    public const int OnEntityFieldNumber = 6;
    private bool onEntity_;
    /// <summary>
    ///是否跟随运动
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OnEntity {
      get { if ((_hasBits0 & 8) != 0) { return onEntity_; } else { return false; } }
      set {
        _hasBits0 |= 8;
        onEntity_ = value;
      }
    }
    /// <summary>Gets whether the "OnEntity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOnEntity {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "OnEntity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOnEntity() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "NeedHight" field.</summary>
    public const int NeedHightFieldNumber = 7;
    private bool needHight_;
    /// <summary>
    ///是否需要跟随角色高度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NeedHight {
      get { if ((_hasBits0 & 16) != 0) { return needHight_; } else { return false; } }
      set {
        _hasBits0 |= 16;
        needHight_ = value;
      }
    }
    /// <summary>Gets whether the "NeedHight" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNeedHight {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "NeedHight" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNeedHight() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "PosName" field.</summary>
    public const int PosNameFieldNumber = 8;
    private string posName_;
    /// <summary>
    ///挂点
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PosName {
      get { return posName_ ?? ""; }
      set {
        posName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "PosName" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPosName {
      get { return posName_ != null; }
    }
    /// <summary>Clears the value of the "PosName" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPosName() {
      posName_ = null;
    }

    /// <summary>Field number for the "NoRepeatAdd" field.</summary>
    public const int NoRepeatAddFieldNumber = 9;
    private bool noRepeatAdd_;
    /// <summary>
    ///不重复叠加
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NoRepeatAdd {
      get { if ((_hasBits0 & 32) != 0) { return noRepeatAdd_; } else { return false; } }
      set {
        _hasBits0 |= 32;
        noRepeatAdd_ = value;
      }
    }
    /// <summary>Gets whether the "NoRepeatAdd" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNoRepeatAdd {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "NoRepeatAdd" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNoRepeatAdd() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "AdiustSkillHeight" field.</summary>
    public const int AdiustSkillHeightFieldNumber = 10;
    private bool adiustSkillHeight_;
    /// <summary>
    ///调节技能时高度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AdiustSkillHeight {
      get { if ((_hasBits0 & 64) != 0) { return adiustSkillHeight_; } else { return false; } }
      set {
        _hasBits0 |= 64;
        adiustSkillHeight_ = value;
      }
    }
    /// <summary>Gets whether the "AdiustSkillHeight" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAdiustSkillHeight {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "AdiustSkillHeight" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAdiustSkillHeight() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "ScaleWithUnit" field.</summary>
    public const int ScaleWithUnitFieldNumber = 11;
    private bool scaleWithUnit_;
    /// <summary>
    ///根据角色缩放
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ScaleWithUnit {
      get { if ((_hasBits0 & 128) != 0) { return scaleWithUnit_; } else { return false; } }
      set {
        _hasBits0 |= 128;
        scaleWithUnit_ = value;
      }
    }
    /// <summary>Gets whether the "ScaleWithUnit" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasScaleWithUnit {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "ScaleWithUnit" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearScaleWithUnit() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "ShowGroupDiff" field.</summary>
    public const int ShowGroupDiffFieldNumber = 12;
    private bool showGroupDiff_;
    /// <summary>
    ///阵营颜色区分
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ShowGroupDiff {
      get { if ((_hasBits0 & 256) != 0) { return showGroupDiff_; } else { return false; } }
      set {
        _hasBits0 |= 256;
        showGroupDiff_ = value;
      }
    }
    /// <summary>Gets whether the "ShowGroupDiff" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasShowGroupDiff {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "ShowGroupDiff" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearShowGroupDiff() {
      _hasBits0 &= ~256;
    }

    /// <summary>Field number for the "HasTrail" field.</summary>
    public const int HasTrailFieldNumber = 13;
    private bool hasTrail_;
    /// <summary>
    ///是否查找拖尾
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTrail {
      get { if ((_hasBits0 & 512) != 0) { return hasTrail_; } else { return false; } }
      set {
        _hasBits0 |= 512;
        hasTrail_ = value;
      }
    }
    /// <summary>Gets whether the "HasTrail" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasHasTrail {
      get { return (_hasBits0 & 512) != 0; }
    }
    /// <summary>Clears the value of the "HasTrail" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearHasTrail() {
      _hasBits0 &= ~512;
    }

    /// <summary>Field number for the "DeadLeftTime" field.</summary>
    public const int DeadLeftTimeFieldNumber = 14;
    private uint deadLeftTime_;
    /// <summary>
    ///特效end后残留时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DeadLeftTime {
      get { if ((_hasBits0 & 1024) != 0) { return deadLeftTime_; } else { return 0; } }
      set {
        _hasBits0 |= 1024;
        deadLeftTime_ = value;
      }
    }
    /// <summary>Gets whether the "DeadLeftTime" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDeadLeftTime {
      get { return (_hasBits0 & 1024) != 0; }
    }
    /// <summary>Clears the value of the "DeadLeftTime" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDeadLeftTime() {
      _hasBits0 &= ~1024;
    }

    /// <summary>Field number for the "NotRemoveOnSkillOver" field.</summary>
    public const int NotRemoveOnSkillOverFieldNumber = 15;
    private bool notRemoveOnSkillOver_;
    /// <summary>
    ///技能结束后不移除
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NotRemoveOnSkillOver {
      get { if ((_hasBits0 & 2048) != 0) { return notRemoveOnSkillOver_; } else { return false; } }
      set {
        _hasBits0 |= 2048;
        notRemoveOnSkillOver_ = value;
      }
    }
    /// <summary>Gets whether the "NotRemoveOnSkillOver" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNotRemoveOnSkillOver {
      get { return (_hasBits0 & 2048) != 0; }
    }
    /// <summary>Clears the value of the "NotRemoveOnSkillOver" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNotRemoveOnSkillOver() {
      _hasBits0 &= ~2048;
    }

    /// <summary>Field number for the "RemoveOnSkillActionOver" field.</summary>
    public const int RemoveOnSkillActionOverFieldNumber = 16;
    private bool removeOnSkillActionOver_;
    /// <summary>
    ///技能动作结束移除
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool RemoveOnSkillActionOver {
      get { if ((_hasBits0 & 4096) != 0) { return removeOnSkillActionOver_; } else { return false; } }
      set {
        _hasBits0 |= 4096;
        removeOnSkillActionOver_ = value;
      }
    }
    /// <summary>Gets whether the "RemoveOnSkillActionOver" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRemoveOnSkillActionOver {
      get { return (_hasBits0 & 4096) != 0; }
    }
    /// <summary>Clears the value of the "RemoveOnSkillActionOver" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRemoveOnSkillActionOver() {
      _hasBits0 &= ~4096;
    }

    /// <summary>Field number for the "Priorty" field.</summary>
    public const int PriortyFieldNumber = 17;
    private int priorty_;
    /// <summary>
    ///同一顿优先级越小越高
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Priorty {
      get { if ((_hasBits0 & 8192) != 0) { return priorty_; } else { return 0; } }
      set {
        _hasBits0 |= 8192;
        priorty_ = value;
      }
    }
    /// <summary>Gets whether the "Priorty" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPriorty {
      get { return (_hasBits0 & 8192) != 0; }
    }
    /// <summary>Clears the value of the "Priorty" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPriorty() {
      _hasBits0 &= ~8192;
    }

    /// <summary>Field number for the "EffectOverTypes" field.</summary>
    public const int EffectOverTypesFieldNumber = 18;
    private static readonly pb::FieldCodec<global::SkillnewConfig.EOverType> _repeated_effectOverTypes_codec
        = pb::FieldCodec.ForEnum(146, x => (int) x, x => (global::SkillnewConfig.EOverType) x);
    private readonly pbc::RepeatedField<global::SkillnewConfig.EOverType> effectOverTypes_ = new pbc::RepeatedField<global::SkillnewConfig.EOverType>();
    /// <summary>
    ///特效结束类型(至少一个)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SkillnewConfig.EOverType> EffectOverTypes {
      get { return effectOverTypes_; }
    }

    /// <summary>Field number for the "EffectEndGameEvents" field.</summary>
    public const int EffectEndGameEventsFieldNumber = 19;
    private static readonly pb::FieldCodec<global::SkillnewConfig.EEntityGameEvent> _repeated_effectEndGameEvents_codec
        = pb::FieldCodec.ForEnum(154, x => (int) x, x => (global::SkillnewConfig.EEntityGameEvent) x);
    private readonly pbc::RepeatedField<global::SkillnewConfig.EEntityGameEvent> effectEndGameEvents_ = new pbc::RepeatedField<global::SkillnewConfig.EEntityGameEvent>();
    /// <summary>
    ///特效结束事件
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::SkillnewConfig.EEntityGameEvent> EffectEndGameEvents {
      get { return effectEndGameEvents_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as effect_data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(effect_data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Path != other.Path) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Scale, other.Scale)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(LifeTime, other.LifeTime)) return false;
      if (OnEntity != other.OnEntity) return false;
      if (NeedHight != other.NeedHight) return false;
      if (PosName != other.PosName) return false;
      if (NoRepeatAdd != other.NoRepeatAdd) return false;
      if (AdiustSkillHeight != other.AdiustSkillHeight) return false;
      if (ScaleWithUnit != other.ScaleWithUnit) return false;
      if (ShowGroupDiff != other.ShowGroupDiff) return false;
      if (HasTrail != other.HasTrail) return false;
      if (DeadLeftTime != other.DeadLeftTime) return false;
      if (NotRemoveOnSkillOver != other.NotRemoveOnSkillOver) return false;
      if (RemoveOnSkillActionOver != other.RemoveOnSkillActionOver) return false;
      if (Priorty != other.Priorty) return false;
      if(!effectOverTypes_.Equals(other.effectOverTypes_)) return false;
      if(!effectEndGameEvents_.Equals(other.effectEndGameEvents_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasPath) hash ^= Path.GetHashCode();
      if (HasScale) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Scale);
      if (HasLifeTime) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(LifeTime);
      if (HasOnEntity) hash ^= OnEntity.GetHashCode();
      if (HasNeedHight) hash ^= NeedHight.GetHashCode();
      if (HasPosName) hash ^= PosName.GetHashCode();
      if (HasNoRepeatAdd) hash ^= NoRepeatAdd.GetHashCode();
      if (HasAdiustSkillHeight) hash ^= AdiustSkillHeight.GetHashCode();
      if (HasScaleWithUnit) hash ^= ScaleWithUnit.GetHashCode();
      if (HasShowGroupDiff) hash ^= ShowGroupDiff.GetHashCode();
      if (HasHasTrail) hash ^= HasTrail.GetHashCode();
      if (HasDeadLeftTime) hash ^= DeadLeftTime.GetHashCode();
      if (HasNotRemoveOnSkillOver) hash ^= NotRemoveOnSkillOver.GetHashCode();
      if (HasRemoveOnSkillActionOver) hash ^= RemoveOnSkillActionOver.GetHashCode();
      if (HasPriorty) hash ^= Priorty.GetHashCode();
      hash ^= effectOverTypes_.GetHashCode();
      hash ^= effectEndGameEvents_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasPath) {
        output.WriteRawTag(26);
        output.WriteString(Path);
      }
      if (HasScale) {
        output.WriteRawTag(37);
        output.WriteFloat(Scale);
      }
      if (HasLifeTime) {
        output.WriteRawTag(45);
        output.WriteFloat(LifeTime);
      }
      if (HasOnEntity) {
        output.WriteRawTag(48);
        output.WriteBool(OnEntity);
      }
      if (HasNeedHight) {
        output.WriteRawTag(56);
        output.WriteBool(NeedHight);
      }
      if (HasPosName) {
        output.WriteRawTag(66);
        output.WriteString(PosName);
      }
      if (HasNoRepeatAdd) {
        output.WriteRawTag(72);
        output.WriteBool(NoRepeatAdd);
      }
      if (HasAdiustSkillHeight) {
        output.WriteRawTag(80);
        output.WriteBool(AdiustSkillHeight);
      }
      if (HasScaleWithUnit) {
        output.WriteRawTag(88);
        output.WriteBool(ScaleWithUnit);
      }
      if (HasShowGroupDiff) {
        output.WriteRawTag(96);
        output.WriteBool(ShowGroupDiff);
      }
      if (HasHasTrail) {
        output.WriteRawTag(104);
        output.WriteBool(HasTrail);
      }
      if (HasDeadLeftTime) {
        output.WriteRawTag(112);
        output.WriteUInt32(DeadLeftTime);
      }
      if (HasNotRemoveOnSkillOver) {
        output.WriteRawTag(120);
        output.WriteBool(NotRemoveOnSkillOver);
      }
      if (HasRemoveOnSkillActionOver) {
        output.WriteRawTag(128, 1);
        output.WriteBool(RemoveOnSkillActionOver);
      }
      if (HasPriorty) {
        output.WriteRawTag(136, 1);
        output.WriteInt32(Priorty);
      }
      effectOverTypes_.WriteTo(output, _repeated_effectOverTypes_codec);
      effectEndGameEvents_.WriteTo(output, _repeated_effectEndGameEvents_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasPath) {
        output.WriteRawTag(26);
        output.WriteString(Path);
      }
      if (HasScale) {
        output.WriteRawTag(37);
        output.WriteFloat(Scale);
      }
      if (HasLifeTime) {
        output.WriteRawTag(45);
        output.WriteFloat(LifeTime);
      }
      if (HasOnEntity) {
        output.WriteRawTag(48);
        output.WriteBool(OnEntity);
      }
      if (HasNeedHight) {
        output.WriteRawTag(56);
        output.WriteBool(NeedHight);
      }
      if (HasPosName) {
        output.WriteRawTag(66);
        output.WriteString(PosName);
      }
      if (HasNoRepeatAdd) {
        output.WriteRawTag(72);
        output.WriteBool(NoRepeatAdd);
      }
      if (HasAdiustSkillHeight) {
        output.WriteRawTag(80);
        output.WriteBool(AdiustSkillHeight);
      }
      if (HasScaleWithUnit) {
        output.WriteRawTag(88);
        output.WriteBool(ScaleWithUnit);
      }
      if (HasShowGroupDiff) {
        output.WriteRawTag(96);
        output.WriteBool(ShowGroupDiff);
      }
      if (HasHasTrail) {
        output.WriteRawTag(104);
        output.WriteBool(HasTrail);
      }
      if (HasDeadLeftTime) {
        output.WriteRawTag(112);
        output.WriteUInt32(DeadLeftTime);
      }
      if (HasNotRemoveOnSkillOver) {
        output.WriteRawTag(120);
        output.WriteBool(NotRemoveOnSkillOver);
      }
      if (HasRemoveOnSkillActionOver) {
        output.WriteRawTag(128, 1);
        output.WriteBool(RemoveOnSkillActionOver);
      }
      if (HasPriorty) {
        output.WriteRawTag(136, 1);
        output.WriteInt32(Priorty);
      }
      effectOverTypes_.WriteTo(ref output, _repeated_effectOverTypes_codec);
      effectEndGameEvents_.WriteTo(ref output, _repeated_effectEndGameEvents_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasPath) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      if (HasScale) {
        size += 1 + 4;
      }
      if (HasLifeTime) {
        size += 1 + 4;
      }
      if (HasOnEntity) {
        size += 1 + 1;
      }
      if (HasNeedHight) {
        size += 1 + 1;
      }
      if (HasPosName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PosName);
      }
      if (HasNoRepeatAdd) {
        size += 1 + 1;
      }
      if (HasAdiustSkillHeight) {
        size += 1 + 1;
      }
      if (HasScaleWithUnit) {
        size += 1 + 1;
      }
      if (HasShowGroupDiff) {
        size += 1 + 1;
      }
      if (HasHasTrail) {
        size += 1 + 1;
      }
      if (HasDeadLeftTime) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DeadLeftTime);
      }
      if (HasNotRemoveOnSkillOver) {
        size += 1 + 1;
      }
      if (HasRemoveOnSkillActionOver) {
        size += 2 + 1;
      }
      if (HasPriorty) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Priorty);
      }
      size += effectOverTypes_.CalculateSize(_repeated_effectOverTypes_codec);
      size += effectEndGameEvents_.CalculateSize(_repeated_effectEndGameEvents_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(effect_data other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasPath) {
        Path = other.Path;
      }
      if (other.HasScale) {
        Scale = other.Scale;
      }
      if (other.HasLifeTime) {
        LifeTime = other.LifeTime;
      }
      if (other.HasOnEntity) {
        OnEntity = other.OnEntity;
      }
      if (other.HasNeedHight) {
        NeedHight = other.NeedHight;
      }
      if (other.HasPosName) {
        PosName = other.PosName;
      }
      if (other.HasNoRepeatAdd) {
        NoRepeatAdd = other.NoRepeatAdd;
      }
      if (other.HasAdiustSkillHeight) {
        AdiustSkillHeight = other.AdiustSkillHeight;
      }
      if (other.HasScaleWithUnit) {
        ScaleWithUnit = other.ScaleWithUnit;
      }
      if (other.HasShowGroupDiff) {
        ShowGroupDiff = other.ShowGroupDiff;
      }
      if (other.HasHasTrail) {
        HasTrail = other.HasTrail;
      }
      if (other.HasDeadLeftTime) {
        DeadLeftTime = other.DeadLeftTime;
      }
      if (other.HasNotRemoveOnSkillOver) {
        NotRemoveOnSkillOver = other.NotRemoveOnSkillOver;
      }
      if (other.HasRemoveOnSkillActionOver) {
        RemoveOnSkillActionOver = other.RemoveOnSkillActionOver;
      }
      if (other.HasPriorty) {
        Priorty = other.Priorty;
      }
      effectOverTypes_.Add(other.effectOverTypes_);
      effectEndGameEvents_.Add(other.effectEndGameEvents_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Path = input.ReadString();
            break;
          }
          case 37: {
            Scale = input.ReadFloat();
            break;
          }
          case 45: {
            LifeTime = input.ReadFloat();
            break;
          }
          case 48: {
            OnEntity = input.ReadBool();
            break;
          }
          case 56: {
            NeedHight = input.ReadBool();
            break;
          }
          case 66: {
            PosName = input.ReadString();
            break;
          }
          case 72: {
            NoRepeatAdd = input.ReadBool();
            break;
          }
          case 80: {
            AdiustSkillHeight = input.ReadBool();
            break;
          }
          case 88: {
            ScaleWithUnit = input.ReadBool();
            break;
          }
          case 96: {
            ShowGroupDiff = input.ReadBool();
            break;
          }
          case 104: {
            HasTrail = input.ReadBool();
            break;
          }
          case 112: {
            DeadLeftTime = input.ReadUInt32();
            break;
          }
          case 120: {
            NotRemoveOnSkillOver = input.ReadBool();
            break;
          }
          case 128: {
            RemoveOnSkillActionOver = input.ReadBool();
            break;
          }
          case 136: {
            Priorty = input.ReadInt32();
            break;
          }
          case 146:
          case 144: {
            effectOverTypes_.AddEntriesFrom(input, _repeated_effectOverTypes_codec);
            break;
          }
          case 154:
          case 152: {
            effectEndGameEvents_.AddEntriesFrom(input, _repeated_effectEndGameEvents_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Path = input.ReadString();
            break;
          }
          case 37: {
            Scale = input.ReadFloat();
            break;
          }
          case 45: {
            LifeTime = input.ReadFloat();
            break;
          }
          case 48: {
            OnEntity = input.ReadBool();
            break;
          }
          case 56: {
            NeedHight = input.ReadBool();
            break;
          }
          case 66: {
            PosName = input.ReadString();
            break;
          }
          case 72: {
            NoRepeatAdd = input.ReadBool();
            break;
          }
          case 80: {
            AdiustSkillHeight = input.ReadBool();
            break;
          }
          case 88: {
            ScaleWithUnit = input.ReadBool();
            break;
          }
          case 96: {
            ShowGroupDiff = input.ReadBool();
            break;
          }
          case 104: {
            HasTrail = input.ReadBool();
            break;
          }
          case 112: {
            DeadLeftTime = input.ReadUInt32();
            break;
          }
          case 120: {
            NotRemoveOnSkillOver = input.ReadBool();
            break;
          }
          case 128: {
            RemoveOnSkillActionOver = input.ReadBool();
            break;
          }
          case 136: {
            Priorty = input.ReadInt32();
            break;
          }
          case 146:
          case 144: {
            effectOverTypes_.AddEntriesFrom(ref input, _repeated_effectOverTypes_codec);
            break;
          }
          case 154:
          case 152: {
            effectEndGameEvents_.AddEntriesFrom(ref input, _repeated_effectEndGameEvents_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class container : pb::IMessage<container>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<container> _parser = new pb::MessageParser<container>(() => new container());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<container> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EffectConfig.EffectConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container(container other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      buildId_ = other.buildId_;
      infos_ = other.infos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container Clone() {
      return new container(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? ""; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "build_id" field.</summary>
    public const int BuildIdFieldNumber = 2;
    private int buildId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BuildId {
      get { if ((_hasBits0 & 1) != 0) { return buildId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        buildId_ = value;
      }
    }
    /// <summary>Gets whether the "build_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBuildId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "build_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBuildId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 3;
    private static readonly pbc::MapField<int, global::EffectConfig.effect_data>.Codec _map_infos_codec
        = new pbc::MapField<int, global::EffectConfig.effect_data>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::EffectConfig.effect_data.Parser), 26);
    private readonly pbc::MapField<int, global::EffectConfig.effect_data> infos_ = new pbc::MapField<int, global::EffectConfig.effect_data>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::EffectConfig.effect_data> Infos {
      get { return infos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as container);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(container other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (BuildId != other.BuildId) return false;
      if (!Infos.Equals(other.Infos)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (HasBuildId) hash ^= BuildId.GetHashCode();
      hash ^= Infos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasBuildId) {
        output.WriteRawTag(16);
        output.WriteInt32(BuildId);
      }
      infos_.WriteTo(output, _map_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasBuildId) {
        output.WriteRawTag(16);
        output.WriteInt32(BuildId);
      }
      infos_.WriteTo(ref output, _map_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasBuildId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuildId);
      }
      size += infos_.CalculateSize(_map_infos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(container other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasBuildId) {
        BuildId = other.BuildId;
      }
      infos_.Add(other.infos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            BuildId = input.ReadInt32();
            break;
          }
          case 26: {
            infos_.AddEntriesFrom(input, _map_infos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            BuildId = input.ReadInt32();
            break;
          }
          case 26: {
            infos_.AddEntriesFrom(ref input, _map_infos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
