// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: resource_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ResourceConfig {

  /// <summary>Holder for reflection information generated from resource_config.proto</summary>
  public static partial class ResourceConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for resource_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResourceConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVyZXNvdXJjZV9jb25maWcucHJvdG8SD3Jlc291cmNlX2NvbmZpZyKUBAoK",
            "bW9kZWxfcGF0aBIRCgRkZXNjGAEgASgJSACIAQESMQoGYXZhdGFyGAIgASgO",
            "MhwucmVzb3VyY2VfY29uZmlnLmF2YXRhcl90eXBlSAGIAQESEQoEcGF0aBgD",
            "IAEoCUgCiAEBEiwKCHVpb2Zmc2V0GAQgASgLMhUucmVzb3VyY2VfY29uZmln",
            "LnZlYzNIA4gBARIUCgd1aXNjYWxlGAUgASgCSASIAQESLwoLc2NlbmVvZmZz",
            "ZXQYBiABKAsyFS5yZXNvdXJjZV9jb25maWcudmVjM0gFiAEBEhcKCnNjZW5l",
            "c2NhbGUYByABKAJIBogBARIsCghzY2VuZXJvdBgIIAEoCzIVLnJlc291cmNl",
            "X2NvbmZpZy52ZWMzSAeIAQESLwoLdWlzZWNvZmZzZXQYCSABKAsyFS5yZXNv",
            "dXJjZV9jb25maWcudmVjM0gIiAEBEhcKCnVpc2Vjc2NhbGUYCiABKAJICYgB",
            "ARIXCgppc0hpZGVXaW5nGAsgASgISAqIAQFCBwoFX2Rlc2NCCQoHX2F2YXRh",
            "ckIHCgVfcGF0aEILCglfdWlvZmZzZXRCCgoIX3Vpc2NhbGVCDgoMX3NjZW5l",
            "b2Zmc2V0Qg0KC19zY2VuZXNjYWxlQgsKCV9zY2VuZXJvdEIOCgxfdWlzZWNv",
            "ZmZzZXRCDQoLX3Vpc2Vjc2NhbGVCDQoLX2lzSGlkZVdpbmciSAoEdmVjMxIO",
            "CgF4GAEgASgCSACIAQESDgoBeRgCIAEoAkgBiAEBEg4KAXoYAyABKAJIAogB",
            "AUIECgJfeEIECgJfeUIECgJfeiLEAQoNcmVzb3VyY2VfZGF0YRIUCgdtZXRh",
            "X2lkGAEgASgFSACIAQESEQoEZGVzYxgCIAEoCUgBiAEBEhYKCW1haW5fcGF0",
            "aBgDIAEoCUgCiAEBEhUKCHN1Yl9wYXRoGAQgASgJSAOIAQESKwoGbW9kZWxz",
            "GAUgAygLMhsucmVzb3VyY2VfY29uZmlnLm1vZGVsX3BhdGhCCgoIX21ldGFf",
            "aWRCBwoFX2Rlc2NCDAoKX21haW5fcGF0aEILCglfc3ViX3BhdGgizwEKCWNv",
            "bnRhaW5lchIRCgRuYW1lGAEgASgJSACIAQESFQoIYnVpbGRfaWQYAiABKAVI",
            "AYgBARI0CgVpbmZvcxgDIAMoCzIlLnJlc291cmNlX2NvbmZpZy5jb250YWlu",
            "ZXIuSW5mb3NFbnRyeRpMCgpJbmZvc0VudHJ5EgsKA2tleRgBIAEoBRItCgV2",
            "YWx1ZRgCIAEoCzIeLnJlc291cmNlX2NvbmZpZy5yZXNvdXJjZV9kYXRhOgI4",
            "AUIHCgVfbmFtZUILCglfYnVpbGRfaWQqlwEKC2F2YXRhcl90eXBlEhAKDGF2",
            "YXRhcl9iZWdpbhAAEggKBGZhY2UQARIICgRoZWFkEAISDgoKdXBwZXJfYm9k",
            "eRADEg4KCnVuZGVyX2JvZHkQBBILCgd3ZWFwb24xEAUSCgoGc2hpZWxkEAYS",
            "CQoFcmlkZXIQBxIICgR3aW5nEAgSCwoHd2VhcG9uMhAJEgcKA3BldBAKYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ResourceConfig.avatar_type), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ResourceConfig.model_path), global::ResourceConfig.model_path.Parser, new[]{ "Desc", "Avatar", "Path", "Uioffset", "Uiscale", "Sceneoffset", "Scenescale", "Scenerot", "Uisecoffset", "Uisecscale", "IsHideWing" }, new[]{ "Desc", "Avatar", "Path", "Uioffset", "Uiscale", "Sceneoffset", "Scenescale", "Scenerot", "Uisecoffset", "Uisecscale", "IsHideWing" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ResourceConfig.vec3), global::ResourceConfig.vec3.Parser, new[]{ "X", "Y", "Z" }, new[]{ "X", "Y", "Z" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ResourceConfig.resource_data), global::ResourceConfig.resource_data.Parser, new[]{ "MetaId", "Desc", "MainPath", "SubPath", "Models" }, new[]{ "MetaId", "Desc", "MainPath", "SubPath" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ResourceConfig.container), global::ResourceConfig.container.Parser, new[]{ "Name", "BuildId", "Infos" }, new[]{ "Name", "BuildId" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Enums
  public enum avatar_type {
    [pbr::OriginalName("avatar_begin")] AvatarBegin = 0,
    /// <summary>
    ///脸
    /// </summary>
    [pbr::OriginalName("face")] Face = 1,
    /// <summary>
    ///头
    /// </summary>
    [pbr::OriginalName("head")] Head = 2,
    /// <summary>
    ///上半身
    /// </summary>
    [pbr::OriginalName("upper_body")] UpperBody = 3,
    /// <summary>
    ///下半身
    /// </summary>
    [pbr::OriginalName("under_body")] UnderBody = 4,
    /// <summary>
    ///右手武器(头)
    /// </summary>
    [pbr::OriginalName("weapon1")] Weapon1 = 5,
    /// <summary>
    ///左手盾牌
    /// </summary>
    [pbr::OriginalName("shield")] Shield = 6,
    /// <summary>
    ///坐骑
    /// </summary>
    [pbr::OriginalName("rider")] Rider = 7,
    /// <summary>
    ///翅膀
    /// </summary>
    [pbr::OriginalName("wing")] Wing = 8,
    /// <summary>
    ///右手武器(柄)
    /// </summary>
    [pbr::OriginalName("weapon2")] Weapon2 = 9,
    /// <summary>
    ///宠物
    /// </summary>
    [pbr::OriginalName("pet")] Pet = 10,
  }

  #endregion

  #region Messages
  public sealed partial class model_path : pb::IMessage<model_path>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<model_path> _parser = new pb::MessageParser<model_path>(() => new model_path());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<model_path> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ResourceConfig.ResourceConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public model_path() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public model_path(model_path other) : this() {
      _hasBits0 = other._hasBits0;
      desc_ = other.desc_;
      avatar_ = other.avatar_;
      path_ = other.path_;
      uioffset_ = other.uioffset_ != null ? other.uioffset_.Clone() : null;
      uiscale_ = other.uiscale_;
      sceneoffset_ = other.sceneoffset_ != null ? other.sceneoffset_.Clone() : null;
      scenescale_ = other.scenescale_;
      scenerot_ = other.scenerot_ != null ? other.scenerot_.Clone() : null;
      uisecoffset_ = other.uisecoffset_ != null ? other.uisecoffset_.Clone() : null;
      uisecscale_ = other.uisecscale_;
      isHideWing_ = other.isHideWing_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public model_path Clone() {
      return new model_path(this);
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 1;
    private string desc_;
    /// <summary>
    ///注释用
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Desc {
      get { return desc_ ?? ""; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "desc" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDesc {
      get { return desc_ != null; }
    }
    /// <summary>Clears the value of the "desc" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDesc() {
      desc_ = null;
    }

    /// <summary>Field number for the "avatar" field.</summary>
    public const int AvatarFieldNumber = 2;
    private global::ResourceConfig.avatar_type avatar_;
    /// <summary>
    ///外显类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ResourceConfig.avatar_type Avatar {
      get { if ((_hasBits0 & 1) != 0) { return avatar_; } else { return global::ResourceConfig.avatar_type.AvatarBegin; } }
      set {
        _hasBits0 |= 1;
        avatar_ = value;
      }
    }
    /// <summary>Gets whether the "avatar" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAvatar {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "avatar" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAvatar() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 3;
    private string path_;
    /// <summary>
    ///外显路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Path {
      get { return path_ ?? ""; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "path" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPath {
      get { return path_ != null; }
    }
    /// <summary>Clears the value of the "path" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPath() {
      path_ = null;
    }

    /// <summary>Field number for the "uioffset" field.</summary>
    public const int UioffsetFieldNumber = 4;
    private global::ResourceConfig.vec3 uioffset_;
    /// <summary>
    ///UI界面偏移
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ResourceConfig.vec3 Uioffset {
      get { return uioffset_; }
      set {
        uioffset_ = value;
      }
    }

    /// <summary>Field number for the "uiscale" field.</summary>
    public const int UiscaleFieldNumber = 5;
    private float uiscale_;
    /// <summary>
    ///UI界面大小处理
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Uiscale {
      get { if ((_hasBits0 & 2) != 0) { return uiscale_; } else { return 0F; } }
      set {
        _hasBits0 |= 2;
        uiscale_ = value;
      }
    }
    /// <summary>Gets whether the "uiscale" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUiscale {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "uiscale" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUiscale() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "sceneoffset" field.</summary>
    public const int SceneoffsetFieldNumber = 6;
    private global::ResourceConfig.vec3 sceneoffset_;
    /// <summary>
    ///场景中偏移
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ResourceConfig.vec3 Sceneoffset {
      get { return sceneoffset_; }
      set {
        sceneoffset_ = value;
      }
    }

    /// <summary>Field number for the "scenescale" field.</summary>
    public const int ScenescaleFieldNumber = 7;
    private float scenescale_;
    /// <summary>
    ///场景中大小处理
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Scenescale {
      get { if ((_hasBits0 & 4) != 0) { return scenescale_; } else { return 0F; } }
      set {
        _hasBits0 |= 4;
        scenescale_ = value;
      }
    }
    /// <summary>Gets whether the "scenescale" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasScenescale {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "scenescale" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearScenescale() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "scenerot" field.</summary>
    public const int ScenerotFieldNumber = 8;
    private global::ResourceConfig.vec3 scenerot_;
    /// <summary>
    ///场景中旋转
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ResourceConfig.vec3 Scenerot {
      get { return scenerot_; }
      set {
        scenerot_ = value;
      }
    }

    /// <summary>Field number for the "uisecoffset" field.</summary>
    public const int UisecoffsetFieldNumber = 9;
    private global::ResourceConfig.vec3 uisecoffset_;
    /// <summary>
    ///UI界面2偏移
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ResourceConfig.vec3 Uisecoffset {
      get { return uisecoffset_; }
      set {
        uisecoffset_ = value;
      }
    }

    /// <summary>Field number for the "uisecscale" field.</summary>
    public const int UisecscaleFieldNumber = 10;
    private float uisecscale_;
    /// <summary>
    ///UI界面2大小处理
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Uisecscale {
      get { if ((_hasBits0 & 8) != 0) { return uisecscale_; } else { return 0F; } }
      set {
        _hasBits0 |= 8;
        uisecscale_ = value;
      }
    }
    /// <summary>Gets whether the "uisecscale" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUisecscale {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "uisecscale" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUisecscale() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "isHideWing" field.</summary>
    public const int IsHideWingFieldNumber = 11;
    private bool isHideWing_;
    /// <summary>
    ///是否隐藏翅膀(部分坐骑骑着时不显示)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsHideWing {
      get { if ((_hasBits0 & 16) != 0) { return isHideWing_; } else { return false; } }
      set {
        _hasBits0 |= 16;
        isHideWing_ = value;
      }
    }
    /// <summary>Gets whether the "isHideWing" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIsHideWing {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "isHideWing" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIsHideWing() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as model_path);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(model_path other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Desc != other.Desc) return false;
      if (Avatar != other.Avatar) return false;
      if (Path != other.Path) return false;
      if (!object.Equals(Uioffset, other.Uioffset)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Uiscale, other.Uiscale)) return false;
      if (!object.Equals(Sceneoffset, other.Sceneoffset)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Scenescale, other.Scenescale)) return false;
      if (!object.Equals(Scenerot, other.Scenerot)) return false;
      if (!object.Equals(Uisecoffset, other.Uisecoffset)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Uisecscale, other.Uisecscale)) return false;
      if (IsHideWing != other.IsHideWing) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasDesc) hash ^= Desc.GetHashCode();
      if (HasAvatar) hash ^= Avatar.GetHashCode();
      if (HasPath) hash ^= Path.GetHashCode();
      if (uioffset_ != null) hash ^= Uioffset.GetHashCode();
      if (HasUiscale) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Uiscale);
      if (sceneoffset_ != null) hash ^= Sceneoffset.GetHashCode();
      if (HasScenescale) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Scenescale);
      if (scenerot_ != null) hash ^= Scenerot.GetHashCode();
      if (uisecoffset_ != null) hash ^= Uisecoffset.GetHashCode();
      if (HasUisecscale) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Uisecscale);
      if (HasIsHideWing) hash ^= IsHideWing.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasDesc) {
        output.WriteRawTag(10);
        output.WriteString(Desc);
      }
      if (HasAvatar) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Avatar);
      }
      if (HasPath) {
        output.WriteRawTag(26);
        output.WriteString(Path);
      }
      if (uioffset_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Uioffset);
      }
      if (HasUiscale) {
        output.WriteRawTag(45);
        output.WriteFloat(Uiscale);
      }
      if (sceneoffset_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Sceneoffset);
      }
      if (HasScenescale) {
        output.WriteRawTag(61);
        output.WriteFloat(Scenescale);
      }
      if (scenerot_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Scenerot);
      }
      if (uisecoffset_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Uisecoffset);
      }
      if (HasUisecscale) {
        output.WriteRawTag(85);
        output.WriteFloat(Uisecscale);
      }
      if (HasIsHideWing) {
        output.WriteRawTag(88);
        output.WriteBool(IsHideWing);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasDesc) {
        output.WriteRawTag(10);
        output.WriteString(Desc);
      }
      if (HasAvatar) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Avatar);
      }
      if (HasPath) {
        output.WriteRawTag(26);
        output.WriteString(Path);
      }
      if (uioffset_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Uioffset);
      }
      if (HasUiscale) {
        output.WriteRawTag(45);
        output.WriteFloat(Uiscale);
      }
      if (sceneoffset_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Sceneoffset);
      }
      if (HasScenescale) {
        output.WriteRawTag(61);
        output.WriteFloat(Scenescale);
      }
      if (scenerot_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Scenerot);
      }
      if (uisecoffset_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Uisecoffset);
      }
      if (HasUisecscale) {
        output.WriteRawTag(85);
        output.WriteFloat(Uisecscale);
      }
      if (HasIsHideWing) {
        output.WriteRawTag(88);
        output.WriteBool(IsHideWing);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasDesc) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (HasAvatar) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Avatar);
      }
      if (HasPath) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      if (uioffset_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Uioffset);
      }
      if (HasUiscale) {
        size += 1 + 4;
      }
      if (sceneoffset_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sceneoffset);
      }
      if (HasScenescale) {
        size += 1 + 4;
      }
      if (scenerot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Scenerot);
      }
      if (uisecoffset_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Uisecoffset);
      }
      if (HasUisecscale) {
        size += 1 + 4;
      }
      if (HasIsHideWing) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(model_path other) {
      if (other == null) {
        return;
      }
      if (other.HasDesc) {
        Desc = other.Desc;
      }
      if (other.HasAvatar) {
        Avatar = other.Avatar;
      }
      if (other.HasPath) {
        Path = other.Path;
      }
      if (other.uioffset_ != null) {
        if (uioffset_ == null) {
          Uioffset = new global::ResourceConfig.vec3();
        }
        Uioffset.MergeFrom(other.Uioffset);
      }
      if (other.HasUiscale) {
        Uiscale = other.Uiscale;
      }
      if (other.sceneoffset_ != null) {
        if (sceneoffset_ == null) {
          Sceneoffset = new global::ResourceConfig.vec3();
        }
        Sceneoffset.MergeFrom(other.Sceneoffset);
      }
      if (other.HasScenescale) {
        Scenescale = other.Scenescale;
      }
      if (other.scenerot_ != null) {
        if (scenerot_ == null) {
          Scenerot = new global::ResourceConfig.vec3();
        }
        Scenerot.MergeFrom(other.Scenerot);
      }
      if (other.uisecoffset_ != null) {
        if (uisecoffset_ == null) {
          Uisecoffset = new global::ResourceConfig.vec3();
        }
        Uisecoffset.MergeFrom(other.Uisecoffset);
      }
      if (other.HasUisecscale) {
        Uisecscale = other.Uisecscale;
      }
      if (other.HasIsHideWing) {
        IsHideWing = other.IsHideWing;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Desc = input.ReadString();
            break;
          }
          case 16: {
            Avatar = (global::ResourceConfig.avatar_type) input.ReadEnum();
            break;
          }
          case 26: {
            Path = input.ReadString();
            break;
          }
          case 34: {
            if (uioffset_ == null) {
              Uioffset = new global::ResourceConfig.vec3();
            }
            input.ReadMessage(Uioffset);
            break;
          }
          case 45: {
            Uiscale = input.ReadFloat();
            break;
          }
          case 50: {
            if (sceneoffset_ == null) {
              Sceneoffset = new global::ResourceConfig.vec3();
            }
            input.ReadMessage(Sceneoffset);
            break;
          }
          case 61: {
            Scenescale = input.ReadFloat();
            break;
          }
          case 66: {
            if (scenerot_ == null) {
              Scenerot = new global::ResourceConfig.vec3();
            }
            input.ReadMessage(Scenerot);
            break;
          }
          case 74: {
            if (uisecoffset_ == null) {
              Uisecoffset = new global::ResourceConfig.vec3();
            }
            input.ReadMessage(Uisecoffset);
            break;
          }
          case 85: {
            Uisecscale = input.ReadFloat();
            break;
          }
          case 88: {
            IsHideWing = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Desc = input.ReadString();
            break;
          }
          case 16: {
            Avatar = (global::ResourceConfig.avatar_type) input.ReadEnum();
            break;
          }
          case 26: {
            Path = input.ReadString();
            break;
          }
          case 34: {
            if (uioffset_ == null) {
              Uioffset = new global::ResourceConfig.vec3();
            }
            input.ReadMessage(Uioffset);
            break;
          }
          case 45: {
            Uiscale = input.ReadFloat();
            break;
          }
          case 50: {
            if (sceneoffset_ == null) {
              Sceneoffset = new global::ResourceConfig.vec3();
            }
            input.ReadMessage(Sceneoffset);
            break;
          }
          case 61: {
            Scenescale = input.ReadFloat();
            break;
          }
          case 66: {
            if (scenerot_ == null) {
              Scenerot = new global::ResourceConfig.vec3();
            }
            input.ReadMessage(Scenerot);
            break;
          }
          case 74: {
            if (uisecoffset_ == null) {
              Uisecoffset = new global::ResourceConfig.vec3();
            }
            input.ReadMessage(Uisecoffset);
            break;
          }
          case 85: {
            Uisecscale = input.ReadFloat();
            break;
          }
          case 88: {
            IsHideWing = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class vec3 : pb::IMessage<vec3>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<vec3> _parser = new pb::MessageParser<vec3>(() => new vec3());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<vec3> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ResourceConfig.ResourceConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public vec3() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public vec3(vec3 other) : this() {
      _hasBits0 = other._hasBits0;
      x_ = other.x_;
      y_ = other.y_;
      z_ = other.z_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public vec3 Clone() {
      return new vec3(this);
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 1;
    private float x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float X {
      get { if ((_hasBits0 & 1) != 0) { return x_; } else { return 0F; } }
      set {
        _hasBits0 |= 1;
        x_ = value;
      }
    }
    /// <summary>Gets whether the "x" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasX {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "x" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearX() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 2;
    private float y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Y {
      get { if ((_hasBits0 & 2) != 0) { return y_; } else { return 0F; } }
      set {
        _hasBits0 |= 2;
        y_ = value;
      }
    }
    /// <summary>Gets whether the "y" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasY {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "y" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearY() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "z" field.</summary>
    public const int ZFieldNumber = 3;
    private float z_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Z {
      get { if ((_hasBits0 & 4) != 0) { return z_; } else { return 0F; } }
      set {
        _hasBits0 |= 4;
        z_ = value;
      }
    }
    /// <summary>Gets whether the "z" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasZ {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "z" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearZ() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as vec3);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(vec3 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasX) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
      if (HasY) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
      if (HasZ) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasX) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (HasY) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (HasZ) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasX) {
        output.WriteRawTag(13);
        output.WriteFloat(X);
      }
      if (HasY) {
        output.WriteRawTag(21);
        output.WriteFloat(Y);
      }
      if (HasZ) {
        output.WriteRawTag(29);
        output.WriteFloat(Z);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasX) {
        size += 1 + 4;
      }
      if (HasY) {
        size += 1 + 4;
      }
      if (HasZ) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(vec3 other) {
      if (other == null) {
        return;
      }
      if (other.HasX) {
        X = other.X;
      }
      if (other.HasY) {
        Y = other.Y;
      }
      if (other.HasZ) {
        Z = other.Z;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            X = input.ReadFloat();
            break;
          }
          case 21: {
            Y = input.ReadFloat();
            break;
          }
          case 29: {
            Z = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class resource_data : pb::IMessage<resource_data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<resource_data> _parser = new pb::MessageParser<resource_data>(() => new resource_data());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<resource_data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ResourceConfig.ResourceConfigReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public resource_data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public resource_data(resource_data other) : this() {
      _hasBits0 = other._hasBits0;
      metaId_ = other.metaId_;
      desc_ = other.desc_;
      mainPath_ = other.mainPath_;
      subPath_ = other.subPath_;
      models_ = other.models_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public resource_data Clone() {
      return new resource_data(this);
    }

    /// <summary>Field number for the "meta_id" field.</summary>
    public const int MetaIdFieldNumber = 1;
    private int metaId_;
    /// <summary>
    ///获取路径直接对应item data表的id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MetaId {
      get { if ((_hasBits0 & 1) != 0) { return metaId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        metaId_ = value;
      }
    }
    /// <summary>Gets whether the "meta_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMetaId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "meta_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMetaId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "desc" field.</summary>
    public const int DescFieldNumber = 2;
    private string desc_;
    /// <summary>
    ///注释
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Desc {
      get { return desc_ ?? ""; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "desc" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDesc {
      get { return desc_ != null; }
    }
    /// <summary>Clears the value of the "desc" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDesc() {
      desc_ = null;
    }

    /// <summary>Field number for the "main_path" field.</summary>
    public const int MainPathFieldNumber = 3;
    private string mainPath_;
    /// <summary>
    ///主路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MainPath {
      get { return mainPath_ ?? ""; }
      set {
        mainPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "main_path" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMainPath {
      get { return mainPath_ != null; }
    }
    /// <summary>Clears the value of the "main_path" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMainPath() {
      mainPath_ = null;
    }

    /// <summary>Field number for the "sub_path" field.</summary>
    public const int SubPathFieldNumber = 4;
    private string subPath_;
    /// <summary>
    ///支路径主要为:图集里的spriteName
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SubPath {
      get { return subPath_ ?? ""; }
      set {
        subPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "sub_path" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSubPath {
      get { return subPath_ != null; }
    }
    /// <summary>Clears the value of the "sub_path" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSubPath() {
      subPath_ = null;
    }

    /// <summary>Field number for the "models" field.</summary>
    public const int ModelsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::ResourceConfig.model_path> _repeated_models_codec
        = pb::FieldCodec.ForMessage(42, global::ResourceConfig.model_path.Parser);
    private readonly pbc::RepeatedField<global::ResourceConfig.model_path> models_ = new pbc::RepeatedField<global::ResourceConfig.model_path>();
    /// <summary>
    ///外显路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ResourceConfig.model_path> Models {
      get { return models_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as resource_data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(resource_data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MetaId != other.MetaId) return false;
      if (Desc != other.Desc) return false;
      if (MainPath != other.MainPath) return false;
      if (SubPath != other.SubPath) return false;
      if(!models_.Equals(other.models_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasMetaId) hash ^= MetaId.GetHashCode();
      if (HasDesc) hash ^= Desc.GetHashCode();
      if (HasMainPath) hash ^= MainPath.GetHashCode();
      if (HasSubPath) hash ^= SubPath.GetHashCode();
      hash ^= models_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasMetaId) {
        output.WriteRawTag(8);
        output.WriteInt32(MetaId);
      }
      if (HasDesc) {
        output.WriteRawTag(18);
        output.WriteString(Desc);
      }
      if (HasMainPath) {
        output.WriteRawTag(26);
        output.WriteString(MainPath);
      }
      if (HasSubPath) {
        output.WriteRawTag(34);
        output.WriteString(SubPath);
      }
      models_.WriteTo(output, _repeated_models_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasMetaId) {
        output.WriteRawTag(8);
        output.WriteInt32(MetaId);
      }
      if (HasDesc) {
        output.WriteRawTag(18);
        output.WriteString(Desc);
      }
      if (HasMainPath) {
        output.WriteRawTag(26);
        output.WriteString(MainPath);
      }
      if (HasSubPath) {
        output.WriteRawTag(34);
        output.WriteString(SubPath);
      }
      models_.WriteTo(ref output, _repeated_models_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasMetaId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MetaId);
      }
      if (HasDesc) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (HasMainPath) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MainPath);
      }
      if (HasSubPath) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SubPath);
      }
      size += models_.CalculateSize(_repeated_models_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(resource_data other) {
      if (other == null) {
        return;
      }
      if (other.HasMetaId) {
        MetaId = other.MetaId;
      }
      if (other.HasDesc) {
        Desc = other.Desc;
      }
      if (other.HasMainPath) {
        MainPath = other.MainPath;
      }
      if (other.HasSubPath) {
        SubPath = other.SubPath;
      }
      models_.Add(other.models_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MetaId = input.ReadInt32();
            break;
          }
          case 18: {
            Desc = input.ReadString();
            break;
          }
          case 26: {
            MainPath = input.ReadString();
            break;
          }
          case 34: {
            SubPath = input.ReadString();
            break;
          }
          case 42: {
            models_.AddEntriesFrom(input, _repeated_models_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MetaId = input.ReadInt32();
            break;
          }
          case 18: {
            Desc = input.ReadString();
            break;
          }
          case 26: {
            MainPath = input.ReadString();
            break;
          }
          case 34: {
            SubPath = input.ReadString();
            break;
          }
          case 42: {
            models_.AddEntriesFrom(ref input, _repeated_models_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class container : pb::IMessage<container>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<container> _parser = new pb::MessageParser<container>(() => new container());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<container> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ResourceConfig.ResourceConfigReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container(container other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      buildId_ = other.buildId_;
      infos_ = other.infos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container Clone() {
      return new container(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? ""; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "build_id" field.</summary>
    public const int BuildIdFieldNumber = 2;
    private int buildId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BuildId {
      get { if ((_hasBits0 & 1) != 0) { return buildId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        buildId_ = value;
      }
    }
    /// <summary>Gets whether the "build_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBuildId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "build_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBuildId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 3;
    private static readonly pbc::MapField<int, global::ResourceConfig.resource_data>.Codec _map_infos_codec
        = new pbc::MapField<int, global::ResourceConfig.resource_data>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::ResourceConfig.resource_data.Parser), 26);
    private readonly pbc::MapField<int, global::ResourceConfig.resource_data> infos_ = new pbc::MapField<int, global::ResourceConfig.resource_data>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::ResourceConfig.resource_data> Infos {
      get { return infos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as container);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(container other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (BuildId != other.BuildId) return false;
      if (!Infos.Equals(other.Infos)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (HasBuildId) hash ^= BuildId.GetHashCode();
      hash ^= Infos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasBuildId) {
        output.WriteRawTag(16);
        output.WriteInt32(BuildId);
      }
      infos_.WriteTo(output, _map_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasBuildId) {
        output.WriteRawTag(16);
        output.WriteInt32(BuildId);
      }
      infos_.WriteTo(ref output, _map_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasBuildId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuildId);
      }
      size += infos_.CalculateSize(_map_infos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(container other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasBuildId) {
        BuildId = other.BuildId;
      }
      infos_.Add(other.infos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            BuildId = input.ReadInt32();
            break;
          }
          case 26: {
            infos_.AddEntriesFrom(input, _map_infos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            BuildId = input.ReadInt32();
            break;
          }
          case 26: {
            infos_.AddEntriesFrom(ref input, _map_infos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
