// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: shake_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ShakeConfig {

  /// <summary>Holder for reflection information generated from shake_config.proto</summary>
  public static partial class ShakeConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for shake_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShakeConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJzaGFrZV9jb25maWcucHJvdG8SDHNoYWtlX2NvbmZpZyLdAQoKc2hha2Vf",
            "ZGF0YRIUCgdtZXRhX2lkGAEgASgFSACIAQESFgoJYW1wbGl0dWRlGAIgASgC",
            "SAGIAQESFgoJZnJlcXVlbmN5GAMgASgCSAKIAQESFQoIZHVyYXRpb24YBCAB",
            "KAJIA4gBARIvCgllU2hha2VEaXIYBSABKA4yFy5zaGFrZV9jb25maWcuZVNo",
            "YWtlRGlySASIAQFCCgoIX21ldGFfaWRCDAoKX2FtcGxpdHVkZUIMCgpfZnJl",
            "cXVlbmN5QgsKCV9kdXJhdGlvbkIMCgpfZVNoYWtlRGlyIsYBCgljb250YWlu",
            "ZXISEQoEbmFtZRgBIAEoCUgAiAEBEhUKCGJ1aWxkX2lkGAIgASgFSAGIAQES",
            "MQoFaW5mb3MYAyADKAsyIi5zaGFrZV9jb25maWcuY29udGFpbmVyLkluZm9z",
            "RW50cnkaRgoKSW5mb3NFbnRyeRILCgNrZXkYASABKAUSJwoFdmFsdWUYAiAB",
            "KAsyGC5zaGFrZV9jb25maWcuc2hha2VfZGF0YToCOAFCBwoFX25hbWVCCwoJ",
            "X2J1aWxkX2lkKkMKCWVTaGFrZURpchIHCgNhbGwQABIOCgpyaWdodDJsZWZ0",
            "EAESEAoMZm9yd2FyZDJiYWNrEAISCwoHdXAyZG93bhADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ShakeConfig.eShakeDir), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ShakeConfig.shake_data), global::ShakeConfig.shake_data.Parser, new[]{ "MetaId", "Amplitude", "Frequency", "Duration", "EShakeDir" }, new[]{ "MetaId", "Amplitude", "Frequency", "Duration", "EShakeDir" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ShakeConfig.container), global::ShakeConfig.container.Parser, new[]{ "Name", "BuildId", "Infos" }, new[]{ "Name", "BuildId" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///震动方向
  /// </summary>
  public enum eShakeDir {
    /// <summary>
    ///所有方向
    /// </summary>
    [pbr::OriginalName("all")] All = 0,
    /// <summary>
    ///左右
    /// </summary>
    [pbr::OriginalName("right2left")] Right2Left = 1,
    /// <summary>
    ///前后
    /// </summary>
    [pbr::OriginalName("forward2back")] Forward2Back = 2,
    /// <summary>
    ///上下
    /// </summary>
    [pbr::OriginalName("up2down")] Up2Down = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  ///背包物品配置
  /// </summary>
  public sealed partial class shake_data : pb::IMessage<shake_data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<shake_data> _parser = new pb::MessageParser<shake_data>(() => new shake_data());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<shake_data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ShakeConfig.ShakeConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public shake_data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public shake_data(shake_data other) : this() {
      _hasBits0 = other._hasBits0;
      metaId_ = other.metaId_;
      amplitude_ = other.amplitude_;
      frequency_ = other.frequency_;
      duration_ = other.duration_;
      eShakeDir_ = other.eShakeDir_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public shake_data Clone() {
      return new shake_data(this);
    }

    /// <summary>Field number for the "meta_id" field.</summary>
    public const int MetaIdFieldNumber = 1;
    private int metaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MetaId {
      get { if ((_hasBits0 & 1) != 0) { return metaId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        metaId_ = value;
      }
    }
    /// <summary>Gets whether the "meta_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMetaId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "meta_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMetaId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "amplitude" field.</summary>
    public const int AmplitudeFieldNumber = 2;
    private float amplitude_;
    /// <summary>
    ///振幅/米
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Amplitude {
      get { if ((_hasBits0 & 2) != 0) { return amplitude_; } else { return 0F; } }
      set {
        _hasBits0 |= 2;
        amplitude_ = value;
      }
    }
    /// <summary>Gets whether the "amplitude" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAmplitude {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "amplitude" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAmplitude() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "frequency" field.</summary>
    public const int FrequencyFieldNumber = 3;
    private float frequency_;
    /// <summary>
    ///频率/秒震动次数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Frequency {
      get { if ((_hasBits0 & 4) != 0) { return frequency_; } else { return 0F; } }
      set {
        _hasBits0 |= 4;
        frequency_ = value;
      }
    }
    /// <summary>Gets whether the "frequency" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFrequency {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "frequency" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFrequency() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "duration" field.</summary>
    public const int DurationFieldNumber = 4;
    private float duration_;
    /// <summary>
    ///持续时间/秒
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Duration {
      get { if ((_hasBits0 & 8) != 0) { return duration_; } else { return 0F; } }
      set {
        _hasBits0 |= 8;
        duration_ = value;
      }
    }
    /// <summary>Gets whether the "duration" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDuration {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "duration" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDuration() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "eShakeDir" field.</summary>
    public const int EShakeDirFieldNumber = 5;
    private global::ShakeConfig.eShakeDir eShakeDir_;
    /// <summary>
    ///震动方向
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ShakeConfig.eShakeDir EShakeDir {
      get { if ((_hasBits0 & 16) != 0) { return eShakeDir_; } else { return global::ShakeConfig.eShakeDir.All; } }
      set {
        _hasBits0 |= 16;
        eShakeDir_ = value;
      }
    }
    /// <summary>Gets whether the "eShakeDir" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEShakeDir {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "eShakeDir" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEShakeDir() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as shake_data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(shake_data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MetaId != other.MetaId) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Amplitude, other.Amplitude)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Frequency, other.Frequency)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Duration, other.Duration)) return false;
      if (EShakeDir != other.EShakeDir) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasMetaId) hash ^= MetaId.GetHashCode();
      if (HasAmplitude) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Amplitude);
      if (HasFrequency) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Frequency);
      if (HasDuration) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Duration);
      if (HasEShakeDir) hash ^= EShakeDir.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasMetaId) {
        output.WriteRawTag(8);
        output.WriteInt32(MetaId);
      }
      if (HasAmplitude) {
        output.WriteRawTag(21);
        output.WriteFloat(Amplitude);
      }
      if (HasFrequency) {
        output.WriteRawTag(29);
        output.WriteFloat(Frequency);
      }
      if (HasDuration) {
        output.WriteRawTag(37);
        output.WriteFloat(Duration);
      }
      if (HasEShakeDir) {
        output.WriteRawTag(40);
        output.WriteEnum((int) EShakeDir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasMetaId) {
        output.WriteRawTag(8);
        output.WriteInt32(MetaId);
      }
      if (HasAmplitude) {
        output.WriteRawTag(21);
        output.WriteFloat(Amplitude);
      }
      if (HasFrequency) {
        output.WriteRawTag(29);
        output.WriteFloat(Frequency);
      }
      if (HasDuration) {
        output.WriteRawTag(37);
        output.WriteFloat(Duration);
      }
      if (HasEShakeDir) {
        output.WriteRawTag(40);
        output.WriteEnum((int) EShakeDir);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasMetaId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MetaId);
      }
      if (HasAmplitude) {
        size += 1 + 4;
      }
      if (HasFrequency) {
        size += 1 + 4;
      }
      if (HasDuration) {
        size += 1 + 4;
      }
      if (HasEShakeDir) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EShakeDir);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(shake_data other) {
      if (other == null) {
        return;
      }
      if (other.HasMetaId) {
        MetaId = other.MetaId;
      }
      if (other.HasAmplitude) {
        Amplitude = other.Amplitude;
      }
      if (other.HasFrequency) {
        Frequency = other.Frequency;
      }
      if (other.HasDuration) {
        Duration = other.Duration;
      }
      if (other.HasEShakeDir) {
        EShakeDir = other.EShakeDir;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MetaId = input.ReadInt32();
            break;
          }
          case 21: {
            Amplitude = input.ReadFloat();
            break;
          }
          case 29: {
            Frequency = input.ReadFloat();
            break;
          }
          case 37: {
            Duration = input.ReadFloat();
            break;
          }
          case 40: {
            EShakeDir = (global::ShakeConfig.eShakeDir) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MetaId = input.ReadInt32();
            break;
          }
          case 21: {
            Amplitude = input.ReadFloat();
            break;
          }
          case 29: {
            Frequency = input.ReadFloat();
            break;
          }
          case 37: {
            Duration = input.ReadFloat();
            break;
          }
          case 40: {
            EShakeDir = (global::ShakeConfig.eShakeDir) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class container : pb::IMessage<container>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<container> _parser = new pb::MessageParser<container>(() => new container());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<container> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ShakeConfig.ShakeConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container(container other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      buildId_ = other.buildId_;
      infos_ = other.infos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container Clone() {
      return new container(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? ""; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "build_id" field.</summary>
    public const int BuildIdFieldNumber = 2;
    private int buildId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BuildId {
      get { if ((_hasBits0 & 1) != 0) { return buildId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        buildId_ = value;
      }
    }
    /// <summary>Gets whether the "build_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBuildId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "build_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBuildId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 3;
    private static readonly pbc::MapField<int, global::ShakeConfig.shake_data>.Codec _map_infos_codec
        = new pbc::MapField<int, global::ShakeConfig.shake_data>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::ShakeConfig.shake_data.Parser), 26);
    private readonly pbc::MapField<int, global::ShakeConfig.shake_data> infos_ = new pbc::MapField<int, global::ShakeConfig.shake_data>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::ShakeConfig.shake_data> Infos {
      get { return infos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as container);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(container other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (BuildId != other.BuildId) return false;
      if (!Infos.Equals(other.Infos)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (HasBuildId) hash ^= BuildId.GetHashCode();
      hash ^= Infos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasBuildId) {
        output.WriteRawTag(16);
        output.WriteInt32(BuildId);
      }
      infos_.WriteTo(output, _map_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasBuildId) {
        output.WriteRawTag(16);
        output.WriteInt32(BuildId);
      }
      infos_.WriteTo(ref output, _map_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasBuildId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuildId);
      }
      size += infos_.CalculateSize(_map_infos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(container other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasBuildId) {
        BuildId = other.BuildId;
      }
      infos_.Add(other.infos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            BuildId = input.ReadInt32();
            break;
          }
          case 26: {
            infos_.AddEntriesFrom(input, _map_infos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            BuildId = input.ReadInt32();
            break;
          }
          case 26: {
            infos_.AddEntriesFrom(ref input, _map_infos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
