// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: unit_config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UnitConfig {

  /// <summary>Holder for reflection information generated from unit_config.proto</summary>
  public static partial class UnitConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for unit_config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnitConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChF1bml0X2NvbmZpZy5wcm90bxILdW5pdF9jb25maWcaFXJlc291cmNlX2Nv",
            "bmZpZy5wcm90byJwCgphdmF0YXJfc3ViEjEKBmF2YXRlchgBIAEoDjIcLnJl",
            "c291cmNlX2NvbmZpZy5hdmF0YXJfdHlwZUgAiAEBEhYKCW1vZGVsUGF0aBgC",
            "IAEoCUgBiAEBQgkKB19hdmF0ZXJCDAoKX21vZGVsUGF0aCLdAgoJdW5pdF9k",
            "YXRhEg8KAklkGAEgASgFSACIAQESEQoEbmFtZRgCIAEoCUgBiAEBEiwKCFVu",
            "aXRUeXBlGAMgASgOMhUudW5pdF9jb25maWcuVW5pdFR5cGVIAogBARImCgNq",
            "b2IYBCABKA4yFC51bml0X2NvbmZpZy5Kb2JUeXBlSAOIAQESFgoJbW9kZWxQ",
            "YXRoGAUgASgJSASIAQESDgoGc2tpbGxzGAYgAygFEhoKDUFuaW1hdGlvblBh",
            "dGgYByABKAlIBYgBARIvCg5kZWZhdWx0X2F2YXRhchgIIAMoCzIXLnVuaXRf",
            "Y29uZmlnLmF2YXRhcl9zdWISEgoFc2NhbGUYCSABKAJIBogBAUIFCgNfSWRC",
            "BwoFX25hbWVCCwoJX1VuaXRUeXBlQgYKBF9qb2JCDAoKX21vZGVsUGF0aEIQ",
            "Cg5fQW5pbWF0aW9uUGF0aEIICgZfc2NhbGUiwwEKCWNvbnRhaW5lchIRCgRu",
            "YW1lGAEgASgJSACIAQESFQoIYnVpbGRfaWQYAiABKAVIAYgBARIwCgVpbmZv",
            "cxgDIAMoCzIhLnVuaXRfY29uZmlnLmNvbnRhaW5lci5JbmZvc0VudHJ5GkQK",
            "CkluZm9zRW50cnkSCwoDa2V5GAEgASgFEiUKBXZhbHVlGAIgASgLMhYudW5p",
            "dF9jb25maWcudW5pdF9kYXRhOgI4AUIHCgVfbmFtZUILCglfYnVpbGRfaWQq",
            "PAoIVW5pdFR5cGUSEgoOVW5pdFR5cGVfQkVHSU4QABIGCgJQYxABEgcKA05w",
            "YxACEgsKB01vbnN0ZXIQAypnCgdKb2JUeXBlEhEKDUpvYlR5cGVfQkVHSU4Q",
            "ABILCgdXYXJyaW9yEAESCgoGQXJjaGVyEAISDQoJU29yY2VyZXNzEAMSCgoG",
            "Q2xlcmljEAQSDAoIQWNhZGVtaWMQBRIHCgNBbGwQBmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ResourceConfig.ResourceConfigReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::UnitConfig.UnitType), typeof(global::UnitConfig.JobType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::UnitConfig.avatar_sub), global::UnitConfig.avatar_sub.Parser, new[]{ "Avater", "ModelPath" }, new[]{ "Avater", "ModelPath" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UnitConfig.unit_data), global::UnitConfig.unit_data.Parser, new[]{ "Id", "Name", "UnitType", "Job", "ModelPath", "Skills", "AnimationPath", "DefaultAvatar", "Scale" }, new[]{ "Id", "Name", "UnitType", "Job", "ModelPath", "AnimationPath", "Scale" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::UnitConfig.container), global::UnitConfig.container.Parser, new[]{ "Name", "BuildId", "Infos" }, new[]{ "Name", "BuildId" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Enums
  public enum UnitType {
    [pbr::OriginalName("UnitType_BEGIN")] Begin = 0,
    /// <summary>
    ///玩家
    /// </summary>
    [pbr::OriginalName("Pc")] Pc = 1,
    /// <summary>
    ///NPC
    /// </summary>
    [pbr::OriginalName("Npc")] Npc = 2,
    /// <summary>
    ///普通怪
    /// </summary>
    [pbr::OriginalName("Monster")] Monster = 3,
  }

  public enum JobType {
    [pbr::OriginalName("JobType_BEGIN")] Begin = 0,
    /// <summary>
    ///战士
    /// </summary>
    [pbr::OriginalName("Warrior")] Warrior = 1,
    /// <summary>
    ///弓箭手
    /// </summary>
    [pbr::OriginalName("Archer")] Archer = 2,
    /// <summary>
    ///魔法师
    /// </summary>
    [pbr::OriginalName("Sorceress")] Sorceress = 3,
    /// <summary>
    ///牧师
    /// </summary>
    [pbr::OriginalName("Cleric")] Cleric = 4,
    /// <summary>
    ///学者
    /// </summary>
    [pbr::OriginalName("Academic")] Academic = 5,
    [pbr::OriginalName("All")] All = 6,
  }

  #endregion

  #region Messages
  public sealed partial class avatar_sub : pb::IMessage<avatar_sub>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<avatar_sub> _parser = new pb::MessageParser<avatar_sub>(() => new avatar_sub());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<avatar_sub> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UnitConfig.UnitConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public avatar_sub() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public avatar_sub(avatar_sub other) : this() {
      _hasBits0 = other._hasBits0;
      avater_ = other.avater_;
      modelPath_ = other.modelPath_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public avatar_sub Clone() {
      return new avatar_sub(this);
    }

    /// <summary>Field number for the "avater" field.</summary>
    public const int AvaterFieldNumber = 1;
    private global::ResourceConfig.avatar_type avater_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ResourceConfig.avatar_type Avater {
      get { if ((_hasBits0 & 1) != 0) { return avater_; } else { return global::ResourceConfig.avatar_type.AvatarBegin; } }
      set {
        _hasBits0 |= 1;
        avater_ = value;
      }
    }
    /// <summary>Gets whether the "avater" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAvater {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "avater" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAvater() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "modelPath" field.</summary>
    public const int ModelPathFieldNumber = 2;
    private string modelPath_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ModelPath {
      get { return modelPath_ ?? ""; }
      set {
        modelPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "modelPath" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasModelPath {
      get { return modelPath_ != null; }
    }
    /// <summary>Clears the value of the "modelPath" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearModelPath() {
      modelPath_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as avatar_sub);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(avatar_sub other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Avater != other.Avater) return false;
      if (ModelPath != other.ModelPath) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAvater) hash ^= Avater.GetHashCode();
      if (HasModelPath) hash ^= ModelPath.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasAvater) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Avater);
      }
      if (HasModelPath) {
        output.WriteRawTag(18);
        output.WriteString(ModelPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasAvater) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Avater);
      }
      if (HasModelPath) {
        output.WriteRawTag(18);
        output.WriteString(ModelPath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAvater) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Avater);
      }
      if (HasModelPath) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ModelPath);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(avatar_sub other) {
      if (other == null) {
        return;
      }
      if (other.HasAvater) {
        Avater = other.Avater;
      }
      if (other.HasModelPath) {
        ModelPath = other.ModelPath;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Avater = (global::ResourceConfig.avatar_type) input.ReadEnum();
            break;
          }
          case 18: {
            ModelPath = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Avater = (global::ResourceConfig.avatar_type) input.ReadEnum();
            break;
          }
          case 18: {
            ModelPath = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class unit_data : pb::IMessage<unit_data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<unit_data> _parser = new pb::MessageParser<unit_data>(() => new unit_data());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<unit_data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UnitConfig.UnitConfigReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public unit_data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public unit_data(unit_data other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      name_ = other.name_;
      unitType_ = other.unitType_;
      job_ = other.job_;
      modelPath_ = other.modelPath_;
      skills_ = other.skills_.Clone();
      animationPath_ = other.animationPath_;
      defaultAvatar_ = other.defaultAvatar_.Clone();
      scale_ = other.scale_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public unit_data Clone() {
      return new unit_data(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "Id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "Id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? ""; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "UnitType" field.</summary>
    public const int UnitTypeFieldNumber = 3;
    private global::UnitConfig.UnitType unitType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::UnitConfig.UnitType UnitType {
      get { if ((_hasBits0 & 2) != 0) { return unitType_; } else { return global::UnitConfig.UnitType.Begin; } }
      set {
        _hasBits0 |= 2;
        unitType_ = value;
      }
    }
    /// <summary>Gets whether the "UnitType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUnitType {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "UnitType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUnitType() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "job" field.</summary>
    public const int JobFieldNumber = 4;
    private global::UnitConfig.JobType job_;
    /// <summary>
    ///职业
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::UnitConfig.JobType Job {
      get { if ((_hasBits0 & 4) != 0) { return job_; } else { return global::UnitConfig.JobType.Begin; } }
      set {
        _hasBits0 |= 4;
        job_ = value;
      }
    }
    /// <summary>Gets whether the "job" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasJob {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "job" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearJob() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "modelPath" field.</summary>
    public const int ModelPathFieldNumber = 5;
    private string modelPath_;
    /// <summary>
    ///路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ModelPath {
      get { return modelPath_ ?? ""; }
      set {
        modelPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "modelPath" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasModelPath {
      get { return modelPath_ != null; }
    }
    /// <summary>Clears the value of the "modelPath" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearModelPath() {
      modelPath_ = null;
    }

    /// <summary>Field number for the "skills" field.</summary>
    public const int SkillsFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_skills_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> skills_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///技能列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Skills {
      get { return skills_; }
    }

    /// <summary>Field number for the "AnimationPath" field.</summary>
    public const int AnimationPathFieldNumber = 7;
    private string animationPath_;
    /// <summary>
    ///动画路径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AnimationPath {
      get { return animationPath_ ?? ""; }
      set {
        animationPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "AnimationPath" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAnimationPath {
      get { return animationPath_ != null; }
    }
    /// <summary>Clears the value of the "AnimationPath" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAnimationPath() {
      animationPath_ = null;
    }

    /// <summary>Field number for the "default_avatar" field.</summary>
    public const int DefaultAvatarFieldNumber = 8;
    private static readonly pb::FieldCodec<global::UnitConfig.avatar_sub> _repeated_defaultAvatar_codec
        = pb::FieldCodec.ForMessage(66, global::UnitConfig.avatar_sub.Parser);
    private readonly pbc::RepeatedField<global::UnitConfig.avatar_sub> defaultAvatar_ = new pbc::RepeatedField<global::UnitConfig.avatar_sub>();
    /// <summary>
    ///默认的外显
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::UnitConfig.avatar_sub> DefaultAvatar {
      get { return defaultAvatar_; }
    }

    /// <summary>Field number for the "scale" field.</summary>
    public const int ScaleFieldNumber = 9;
    private float scale_;
    /// <summary>
    ///大小
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Scale {
      get { if ((_hasBits0 & 8) != 0) { return scale_; } else { return 0F; } }
      set {
        _hasBits0 |= 8;
        scale_ = value;
      }
    }
    /// <summary>Gets whether the "scale" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasScale {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "scale" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearScale() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as unit_data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(unit_data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (UnitType != other.UnitType) return false;
      if (Job != other.Job) return false;
      if (ModelPath != other.ModelPath) return false;
      if(!skills_.Equals(other.skills_)) return false;
      if (AnimationPath != other.AnimationPath) return false;
      if(!defaultAvatar_.Equals(other.defaultAvatar_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Scale, other.Scale)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasUnitType) hash ^= UnitType.GetHashCode();
      if (HasJob) hash ^= Job.GetHashCode();
      if (HasModelPath) hash ^= ModelPath.GetHashCode();
      hash ^= skills_.GetHashCode();
      if (HasAnimationPath) hash ^= AnimationPath.GetHashCode();
      hash ^= defaultAvatar_.GetHashCode();
      if (HasScale) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Scale);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasUnitType) {
        output.WriteRawTag(24);
        output.WriteEnum((int) UnitType);
      }
      if (HasJob) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Job);
      }
      if (HasModelPath) {
        output.WriteRawTag(42);
        output.WriteString(ModelPath);
      }
      skills_.WriteTo(output, _repeated_skills_codec);
      if (HasAnimationPath) {
        output.WriteRawTag(58);
        output.WriteString(AnimationPath);
      }
      defaultAvatar_.WriteTo(output, _repeated_defaultAvatar_codec);
      if (HasScale) {
        output.WriteRawTag(77);
        output.WriteFloat(Scale);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasUnitType) {
        output.WriteRawTag(24);
        output.WriteEnum((int) UnitType);
      }
      if (HasJob) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Job);
      }
      if (HasModelPath) {
        output.WriteRawTag(42);
        output.WriteString(ModelPath);
      }
      skills_.WriteTo(ref output, _repeated_skills_codec);
      if (HasAnimationPath) {
        output.WriteRawTag(58);
        output.WriteString(AnimationPath);
      }
      defaultAvatar_.WriteTo(ref output, _repeated_defaultAvatar_codec);
      if (HasScale) {
        output.WriteRawTag(77);
        output.WriteFloat(Scale);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasUnitType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UnitType);
      }
      if (HasJob) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Job);
      }
      if (HasModelPath) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ModelPath);
      }
      size += skills_.CalculateSize(_repeated_skills_codec);
      if (HasAnimationPath) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnimationPath);
      }
      size += defaultAvatar_.CalculateSize(_repeated_defaultAvatar_codec);
      if (HasScale) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(unit_data other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasUnitType) {
        UnitType = other.UnitType;
      }
      if (other.HasJob) {
        Job = other.Job;
      }
      if (other.HasModelPath) {
        ModelPath = other.ModelPath;
      }
      skills_.Add(other.skills_);
      if (other.HasAnimationPath) {
        AnimationPath = other.AnimationPath;
      }
      defaultAvatar_.Add(other.defaultAvatar_);
      if (other.HasScale) {
        Scale = other.Scale;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            UnitType = (global::UnitConfig.UnitType) input.ReadEnum();
            break;
          }
          case 32: {
            Job = (global::UnitConfig.JobType) input.ReadEnum();
            break;
          }
          case 42: {
            ModelPath = input.ReadString();
            break;
          }
          case 50:
          case 48: {
            skills_.AddEntriesFrom(input, _repeated_skills_codec);
            break;
          }
          case 58: {
            AnimationPath = input.ReadString();
            break;
          }
          case 66: {
            defaultAvatar_.AddEntriesFrom(input, _repeated_defaultAvatar_codec);
            break;
          }
          case 77: {
            Scale = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            UnitType = (global::UnitConfig.UnitType) input.ReadEnum();
            break;
          }
          case 32: {
            Job = (global::UnitConfig.JobType) input.ReadEnum();
            break;
          }
          case 42: {
            ModelPath = input.ReadString();
            break;
          }
          case 50:
          case 48: {
            skills_.AddEntriesFrom(ref input, _repeated_skills_codec);
            break;
          }
          case 58: {
            AnimationPath = input.ReadString();
            break;
          }
          case 66: {
            defaultAvatar_.AddEntriesFrom(ref input, _repeated_defaultAvatar_codec);
            break;
          }
          case 77: {
            Scale = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class container : pb::IMessage<container>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<container> _parser = new pb::MessageParser<container>(() => new container());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<container> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::UnitConfig.UnitConfigReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container(container other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      buildId_ = other.buildId_;
      infos_ = other.infos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public container Clone() {
      return new container(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? ""; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "build_id" field.</summary>
    public const int BuildIdFieldNumber = 2;
    private int buildId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BuildId {
      get { if ((_hasBits0 & 1) != 0) { return buildId_; } else { return 0; } }
      set {
        _hasBits0 |= 1;
        buildId_ = value;
      }
    }
    /// <summary>Gets whether the "build_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBuildId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "build_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBuildId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "infos" field.</summary>
    public const int InfosFieldNumber = 3;
    private static readonly pbc::MapField<int, global::UnitConfig.unit_data>.Codec _map_infos_codec
        = new pbc::MapField<int, global::UnitConfig.unit_data>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::UnitConfig.unit_data.Parser), 26);
    private readonly pbc::MapField<int, global::UnitConfig.unit_data> infos_ = new pbc::MapField<int, global::UnitConfig.unit_data>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::UnitConfig.unit_data> Infos {
      get { return infos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as container);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(container other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (BuildId != other.BuildId) return false;
      if (!Infos.Equals(other.Infos)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (HasBuildId) hash ^= BuildId.GetHashCode();
      hash ^= Infos.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasBuildId) {
        output.WriteRawTag(16);
        output.WriteInt32(BuildId);
      }
      infos_.WriteTo(output, _map_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasBuildId) {
        output.WriteRawTag(16);
        output.WriteInt32(BuildId);
      }
      infos_.WriteTo(ref output, _map_infos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasBuildId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuildId);
      }
      size += infos_.CalculateSize(_map_infos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(container other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasBuildId) {
        BuildId = other.BuildId;
      }
      infos_.Add(other.infos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            BuildId = input.ReadInt32();
            break;
          }
          case 26: {
            infos_.AddEntriesFrom(input, _map_infos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            BuildId = input.ReadInt32();
            break;
          }
          case 26: {
            infos_.AddEntriesFrom(ref input, _map_infos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
